### ISSUE TITLE
getHtml() returns last fully-synced content instead of current content.

### ISSUE THREAD

**Issue by mikelehen** [firebase/firepad#117]
Via Guy Goldstein: getHtml() appears to return the last synced value, not the last value the user's seen on their screen, which is probably what you'd expect (it's what I want). My fix for that was using the normal doc login in getHtmlFromRange(), changing its first line to this:
    var doc = (start != null && end != null) ? this.getOperationForSpan(start, end) : this.getOperationForSpan(0, this.codeMirror_.getValue().length);

(Unclear to me if that works in Ace via the adapter, or if you'd have to use different logic for Ace. getHtmlFromSelection() uses the codeMirror_ field too.)

**Comment by kofifus** [comment]
Not to reopen this issue but just to add that it is possible/better to get the get the html directly from codemirror without accessing firebase at all.This has the advantage of allowing the user to export his document even when disconnected. Here's sample code (still work in progress):
```
  function getAsHtml() {
    // get cm html
    var cmhtml = '';
    var pres = codeMirror.display.lineDiv.querySelectorAll('pre');
    for (var i = 0; i < pres.length; i++) {
      //<pre class=" CodeMirror-line " style="text-indent: 0px; padding-left: 4px;"><span style="padding-right: 0.1px;">xxx</span></pre>
      var classes = '';
      var numClasses = pres[i].classList.length;
      for (var j = 0; j < numClasses; j++)
        if (pres[i].classList[j] !== 'CodeMirror-line') classes += pres[i].classList[j] + ' ';

      var lineHTML = pres[i].firstChild.innerHTML;
      lineHTML = lineHTML.replace(/^(&nbsp;|\s)+/, function(gap) {
        return gap.replace(/\s/g, '&nbsp;');
      }); // replace spaces in the beginning with &nbsp;
      if (classes !== '') lineHTML = '<span style="display:inline-block;" class="' + classes + '">' + lineHTML + '</span>';

      cmhtml += lineHTML + '<br>';
    }
    cmhtml = cmhtml.replace(/\u200B/g, ''); // remove zero width space char
    cmhtml = cmhtml.replace(/<span cm-text=""><\/span><br>/g, ''); // remove zero width space char

    cmhtml = '<div style="font-family:Verdana,sans-serif;font-size:14px;">' + cmhtml + '</div>';

    var html = makeHtmlFromSegment(cmhtml);
    //console.log(html);
    return html;
  }
```

**Comment by mikelehen** [comment]
@kofifus Can you explain a bit more?  The current implementation already goes directly to codemirror AFAIK.  Are you saying it doesn't work when offline?  That would surprise me.

**Comment by kofifus** [comment]
Perhaps I got it wrong. The current getHtml uses doc.ops so I assumed it goes to the OT model perhaps doc.ops refers to something else ?

The main rational behind my code is that I needed to preserve some styles I added directly to the CM content (remember my hanging indent solution?), since I could not figure out how to modify the current getHtml I made the solution above which goes over codeMirror.display.lineDiv.querySelectorAll('pre'); and massage it a bit. 

So I guess it's more of showing an alternative to the current implementation.

**Comment by cben** [comment]
2016-01-26 22:39 GMT+02:00 Kofifus <notifications@github.com>:

> goes over codeMirror.display.lineDiv.querySelectorAll('pre')
>
I hope you know CM typically doesn't materialize all of its content as
'pre' DOM nodes, only the currently scrolled portion.
You can force CM to create full DOM by setting viewportMargin
<https://codemirror.net/doc/manual.html#option_viewportMargin> to Infinity
but that comes with performance caveats.

**Comment by kofifus** [comment]
true cben, I had to also set viewportMargin to Infinity

however I found no other way when adding styles to CM

**Comment by mikelehen** [comment]
Yeah.  The getHtml() method on firepad is really meant for people using firepad's rich-text capabilities and is meant to generate html that can be re-imported with setHtml().  If you basically want the raw html codemirror is generating, what you did seems reasonable. :-)

**Comment by kofifus** [comment]
Thx Michael ! just to confirm, does getHtml() relays on the Firebase instance being connected or not ?

**Comment by mikelehen** [comment]
It does not.  The firepad instance has to have been connected in the past so it has the initial synced data, but any time after that point getHtml() will immediately return the contents as html, without touching the network.

**Comment by kofifus** [comment]
ok great thanks!
