### ISSUE TITLE
Uncaught Error: The base length of the second operation has to be the target length of the first operation 

### ISSUE THREAD

**Issue by quorth0n** [firebase/firepad#121]
Hello all,
I am using CodeMirror with Firepad to make a collaborative coding poject, and it will work collaboratively until I press the return/enter key and start typing, my edits will not show up on the other pages I have open. I tested in every major browser and the resuts are the same.

Demo: http://jsfiddle.net/e7uc9/11/
(I type `function foo() {` and hit enter and it gives me the error)

Is this a Firepad issue? Or is it something I'm doing wrong in my code? Thank you all in advanced.

~Mulletfingers999

**Comment by arunthampi** [comment]
I see Issue #112 has been closed but I'm still running into this issue (with the latest version of Codemirror -  5.2)

**Comment by mikelehen** [comment]
@arunthampi I'm not aware of any remaining issues with CodeMirror 4.  Can you open a new case with the details of the issue you're hitting?  It'd help if you could confirm whether it's specific to CodeMirror 5.

**Comment by arunthampi** [comment]
@mikelehen just raised an issue: https://github.com/firebase/firepad/issues/167. One caveat is that this error happens only when the CodeMirror mode does auto-indentation (such as `javascript` or `css`) but not in modes such as `markdown`.

**Comment by vincentwoo** [comment]
I can confirm that Firepad is broken on latest Codemirror 5.x - but not its immediate predecessor. I should have filed a report a week ago, but uh, I forgot.
