### ISSUE TITLE
How can i  get it run in openshift?

### ISSUE THREAD

**Issue by tvvocold** [firebase/firepad#159]
here is what i try : 
$rhc app-create firepad nodejs-0.10 
$rhc ssh firepad
$cd app-root/repo
$git clone https://github.com/firebase/firepad.git
$npm install  is working but cannot install grunt and bower    
could i just run npm install and make it run without grunt and bower?
（usually i just need "$node server.js" and make it run.just like [this](https://github.com/spance/AirGoo) )

**Comment by mikelehen** [comment]
You only need to clone the git repo and use grunt if you're trying to build firepad.js.  But typically you'd just use the version from the CDN.  Try following the steps in the docs to get a firepad example going: http://www.firepad.io/docs/
