### ISSUE TITLE
List, indent increase/decrease, paragraph buttons make page crashing

### ISSUE THREAD

**Issue by Clempops** [firebase/firepad#162]
List, indent increase/decrease, paragraph buttons make the page crashing. Others buttons are working correctly. I have imported all js and css files into my rails app.

JS:
```javascript
var firepadRef = new Firebase('myUrl');
var codeMirror = CodeMirror(document.getElementById('firepad'), { lineWrapping: true });
var firepad = Firepad.fromCodeMirror(firepadRef, codeMirror,
	  	{ richTextToolbar: true, richTextShortcuts: true, defaultText: 'Hello, World!'});
```

**Comment by mikelehen** [comment]
Does the demo on www.firepad.io work for you?  It's using basically that same code.

**Comment by Clempops** [comment]
Yes it works

**Comment by mikelehen** [comment]
Okay.  That means there must be something extra in your code that is causing firepad to not work for you.  Can you provide a link to your broken firepad so that I may take a look?

**Comment by Clempops** [comment]
Actually that was my assets tree that wasn't correct. With the html tags it works ;) thanks !

**Comment by mikelehen** [comment]
Great to hear.  I'll close this out.
