### ISSUE TITLE
Firepad: Invalid Operation

### ISSUE THREAD

**Issue by arunthampi** [firebase/firepad#165]
Started getting this error in the Chrome web console: `Firepad: Invalid operation. https://xxx.firebaseio.com/posts/QbbLbpDgvtFyeMruKN-pLQ A0 Object {a: 1, o: Array[1], t: 1427255835927}` Could it mean I've hit some kind of usage limit?

**Comment by mikelehen** [comment]
Hrm, no...  That means there was an operation in Firebase that we couldn't parse.  Unfortunately it's probably the 'o' field, which we can't see the contents of in the log message. :-/  But that'd be the thing to dig into.
