### ISSUE TITLE
Firepad doesn't work with CodeMirror 5.x

### ISSUE THREAD

**Issue by arunthampi** [firebase/firepad#167]
The same error happens as detailed in #121, on both CodeMirror 5.0 and 5.2.

The error happens when the return/enter key is pressed and the given CodeMirror mode supports auto-indent, so for e.g. there are no errors when the mode is set to `markdown` but setting it to `javascript` or `css` causes errors.

**Comment by arunthampi** [comment]
Confirmed that this error doesn't exist in CodeMirror 4.5.0

**Comment by mikelehen** [comment]
Thanks.  Updated title to reflect that this is a CM 5.x compatibility issue.  We'll look into it when we get a chance.  In the meantime, if you're able to figure out any additional details (e.g. what changed in CM 5 that could have caused this), let us know!

**Comment by arunthampi** [comment]
Thanks, will do when I get a chance. For now, I've downgraded to CodeMirror 4.13.0 and there are no issues.

**Comment by vincentwoo** [comment]
I can confirm the auto-indenting setting makes a difference. Am doing a bit of digging now.

**Comment by vincentwoo** [comment]
Through the careful application of git bisect, I have been able to determine that changing *just* the line

`CodeMirror.version = "5.2.0";`

to

`CodeMirror.version = "4.13.0";`

is enough to cause the bug not to happen. I am, uh, investigating further.

**Comment by vincentwoo** [comment]
Oh, of course, it's because of the new vs old style changes method. Hahhhh.

**Comment by mikelehen** [comment]
Just released Firepad v1.1.1 with this fix.

**Comment by arunthampi** [comment]
Thanks guys!






On Sat, May 9, 2015 at 11:57 AM -0700, "Michael Lehenbauer" <notifications@github.com> wrote:












Just released Firepad v1.1.1 with this fix.
