### ISSUE TITLE
Example code.html has wrong reference

### ISSUE THREAD

**Issue by mjaque** [firebase/firepad#168]
In my opinion, line 38 should be changed to match var defined in line 36 when changed by user:

                 //// Initialize Firebase.
line 36      var firepadRef = getExampleRef();
                 // TODO: Replace above line with:
line 38      // var ref = new Firebase('<YOUR FIREBASE URL>');

should be
line 38      // var firepadRef = new Firebase('<YOUR FIREBASE URL>');

So newbies like me don't get lost on first try.

**Comment by mikelehen** [comment]
Oops, good catch.  Fixed in master, thanks.
