### ISSUE TITLE
Getting Started Snippets Not Working

### ISSUE THREAD

**Issue by jpgilchrist** [firebase/firepad#174]
Simply copy/paste getting started snippets

    <!DOCTYPE html>
    <html>
    <head lang="en">
        <meta charset="UTF-8">
        <title></title>
    
        <style>
            .firepad {
                width: 700px;
                height: 450px;
                background-color: rgba(11, 9, 13, 0.48); /* dark orange background */
            }
    
            /* Note: CodeMirror applies its own styles which can be customized in the same way.
               To apply a background to the entire editor, we need to also apply it to CodeMirror. */
            .CodeMirror {
                background-color: #f9fffb;
            }
        </style>
    </head>
    <body>
    
    <div id="firepad"></div>
    
    
    <script src="https://cdn.firebase.com/js/client/2.2.4/firebase.js"></script>
    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.2.0/codemirror.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.2.0/codemirror.css" />
    
    
    <link rel="stylesheet" href="https://cdn.firebase.com/libs/firepad/1.1.1/firepad.css" />
    <script src="https://cdn.firebase.com/libs/firepad/1.1.1/firepad.min.js"></script>
    <script>
        var firepadRef = new Firebase('{URL}');
        var codeMirror = CodeMirror(document.getElementById('firepad'), { lineWrapping: true });
        var firepad = Firepad.fromCodeMirror(firepadRef, codeMirror,
                { richTextShortcuts: true, richTextToolbar: true, defaultText: 'Hello, World!' });
    </script>
    </body>
    </html>

results in the following screenshot:

![screen shot 2015-05-22 at 4 09 51 pm](https://cloud.githubusercontent.com/assets/5065660/7778817/0f8d8324-009d-11e5-8b0f-4a9c545f5086.png)

The text area cannot be found (despite it being there in the dom).

**Comment by mikelehen** [comment]
Yeah, this is due to #171.  I noticed it the other day but haven't gotten a chance to fix.
