### ISSUE TITLE
Capslock in UIWebView (iOS)

### ISSUE THREAD

**Issue by D-32** [firebase/firepad#178]
The input for me is always uppercase on iOS. Also when opening the examples in Safari.
`autocapitalize` is set to off inside CodeMirror, but this doesn't seem to work.

**Comment by mikelehen** [comment]
Thanks for the report.  I'd definitely be interested in improving the experience on iOS but not sure when I'll have cycles to do dig into it.  Any chance you can check if the problem happens with CodeMirror alone?  If so, you might want to report the issue on their discussion forum(http://discuss.codemirror.net/).  You might also want to try using the latest CodeMirror if you're not already.

**Comment by D-32** [comment]
Yes, seems to be an issue that codemirror has. I've opened an issue with them: https://github.com/codemirror/CodeMirror/issues/3403
