### ISSUE TITLE
Intergation tests time out on high-latency connection

### ISSUE THREAD

**Issue by cben** [firebase/firepad#183]
Some of the integration tests are timing out for me most of the time, especially "Out-of-order edit".
I figured that's probably because I'm running them from Israel, with higher latency than you expected.
Indeed, from a US machine they easily pass.
The easiest way to reproduce is a digital ocean box in Singapore:
```
ssh firepad@128.199.222.212
Password: firepad
firepad@firepad-tests:~$ cd firepad
firepad@firepad-tests:~$ git checkout master
firepad@firepad-tests:~/firepad$ PHANTOMJS_BIN=/usr/bin/phantomjs grunt test
```

Initially I was mainly getting:
```
WARN [PhantomJS 1.9.0 (Linux 0.0.0)]: Disconnected (1 times), because no message in 10000 ms.
```
so I tried to increase e.g. `browserNoActivityTimeout: 30000,` in `test/karma.conf.js`.
But while this prevents disconnects, I started getting failures instead e.g.:
```
  Integration tests > Out-of-order edit
	timeout: timed out after 5000 msec waiting for Got correct end value.
```
and increasing the timeout in the tests:
```diff
-    waitsFor(function() { return cm2.getValue() === '3456789' }, 'Got correct end value.');
+    waitsFor(function() { return cm2.getValue() === '3456789' }, 'Got correct end value.', 40000);
```
leads to again to disconnect :-(.
At 40sec I don't think it's merely slow link, it seems it has no intention of ever passing.

**Comment by cben** [comment]
Inversigating more, when working from that singapore box, data never reaches firepad.
I'm printing out the refs, e.g. https://firepad-test.firebaseio-demo.com/-Jsv7UclnEYkdTzyd8et but there is no data there.
REST access to firebase (`curl https....json`) works from there.  Strange.

**Comment by cben** [comment]
Dunno what that was.  Cleaned, reinstalled, now reproduces cleanly.  Working on patch...

**Comment by cben** [comment]
Turns out "Out-of-order edit" is not particularly slow — it's just the first integration test and bears the price of connecting to firebase.  If I give it a long timeout, all following integration tests pass with their default 5000ms timeout; if I comment it out, all following integration tests time out (all this given sufficiently long `browserNoActivityTimeout`).

**Comment by mikelehen** [comment]
Thanks Beni,

FWIW, this may be exacerbated by PhantomJS.  I'm not sure if the state of things has changed, but for the longest time it didn't support websockets, which means we use our fallback JSONP long-polling transport, which takes a longer time to connect...

In any case, want to see if this PR (https://github.com/firebase/firepad/pull/184) addresses the issue for you?

**Comment by cben** [comment]
Sorry for disappearing (real life intruded).
#184 is progress; together with increasing `browserNoActivityTimeout` all tests reliably complete.
This exposes a few specific tests that tend to fail:
```
  Integration tests > Uses defaultText to initialize the pad properly
	Expected 'This should be the starting text' to equal 'this is a new, different text'.

  Integration tests > Uses defaultText to initialize the pad properly
	Error: You must wait for the "ready" event before calling getText.
	    at /home/beni/mathdown/firepad/lib/firepad.js:9
	    at /home/beni/mathdown/firepad/lib/firepad.js:9
	    at /home/beni/mathdown/firepad/test/specs/integration.spec.js:140

  Integration tests > Emits sync events as users edit the pad
	Expected false to be true.
```
(the first 2 are alternate failure modes of the same test)
I'll try to investigate further.

**Comment by cben** [comment]
Turned out to be straightforward - these were the only 2 tests using `waits(500)`.  See new PR.
