### ISSUE TITLE
Compatibility with latest Ace (v1.2.0)

### ISSUE THREAD

**Issue by 1j01** [firebase/firepad#197]
[These API changes](https://github.com/ajaxorg/ace/blob/bd67eec06ed7bed48dc0605347424dfe4999b55d/ChangeLog.txt#L7-L9) lead to errors like
```
Uncaught TypeError: Cannot read property 'action' of undefined
  a.ACEAdapter.b.operationFromACEChange
  a.ACEAdapter.b.onChange
  r._signal
  onDocumentChange
```

I might try to work on this (and then possibly https://github.com/firebase/firepad/issues/93).

**Comment by 1j01** [comment]
I'm working on upgrading to Jasmine 2.x.x, converting asynchronous tests to the new syntax.

**Comment by mikelehen** [comment]
Cool, thanks @1j01!

**Comment by 1j01** [comment]
Okay, I have all the tests converted, including several that had "no expectations".
The `coffeelint` task in grunt is set to stop everything on the basis of line endings, so I had to downgrade it to a `"warn"`, but I have `git config --global core.autocrlf` set to `true`, so I don't think this should actually be a problem when committing. Should I set it back to `"error"`, or leave it at `"warn"`?

**Comment by 1j01** [comment]
Here are the changes for review: https://github.com/firebase/firepad/pull/198

**Comment by mikelehen** [comment]
I merged #198.  Would love to see a fix for the Ace stuff now if you're still up for it. :-)

**Comment by 1j01** [comment]
I did take a stab at it, and I got it to pass my very basic test, but it fails when actually using it. I'll probably need to write some better tests. I was kind of hoping I might only need to update this one function to something like this:
```coffee
  operationFromACEChange: (change) ->
    console.log "operationFromACEChange", change
    if change.lines
      text = change.lines.join("\n") + "\n"
      action = change.action.replace "Lines", ""
    else
      console.warn "I don't think this is a case any more"
      text = change.text.replace(@aceDoc.getNewLineCharacter(), '\n')
      action = change.action.replace "Text", ""
    start = @indexFromPos change.start
    restLength = @lastDocLines.join('\n').length - start
    restLength -= text.length if action is "remove"
    insert_op = new firepad.TextOperation().retain(start).insert(text).retain(restLength)
    delete_op = new firepad.TextOperation().retain(start).delete(text).retain(restLength)
    if action is 'remove'
      [delete_op, insert_op]
    else
      [insert_op, delete_op]
```
But I get errors like `sendOperation() called with invalid operation.` and `The base length of the second operation has to be the target length of the first operation`

I'm wondering about that `indexFromPos` function and its usage of `ace.$lines`...

**Comment by 1j01** [comment]
Ah, it seems `text = change.lines.join("\n")` no longer needs the additional `"\n"`

**Comment by 1j01** [comment]
So after much trial and error, it does work! And I only had to change the one function.
Now to update the docs. I'll recommend using firepad 1.2.0 or less for ace less than 1.2.0... hm, that akwardly doesn't line up.

**Comment by mikelehen** [comment]
Good to hear!

Would it be possible to make the change so that it can support new and old versions of ace?  That's what we've done with CodeMirror breaking changes so far and makes it a lot easier for consumers.

**Comment by 1j01** [comment]
Yeah, I was thinking that. It should be pretty easy since it's just one function.

**Comment by 1j01** [comment]
Opened https://github.com/firebase/firepad/pull/201
The ace example should be updated, which I guess you would do once you have published the next version of firepad. And definitely another test or two for integration would be good.

**Comment by mikelehen** [comment]
Awesome, thanks!
