### ISSUE TITLE
Request for clarification on unicode

### ISSUE THREAD

**Issue by vincentwoo** [firebase/firepad#203]
Users will sometimes type stuff like 💩. In JS, the string length of this character is `2`, in Ruby, by default, `1`. The number of bytes in the string is actually 4, because it's a crazy surrogate pair unicode thingy. Editors treat it like a single character and rightly so.

In Firepad's OT implementation, this string has a length of `2` in future retains. This is, I imagine, just because the implementation uses JS default string.length method for calculations. Would you consider this behavior to be correct?

**Comment by vincentwoo** [comment]
Also, https://mathiasbynens.be/notes/javascript-unicode is a terrifying and helpful reference

**Comment by mikelehen** [comment]
Heh.  This definitely sounds expected.  Most modern languages (including JS) use UTF-16 (2-byte) characters and so a surrogate pair will be represented as 2 characters.  I think it's reasonable for firepad to rely on this, though "correct" may be arguable. :-)

**Comment by vincentwoo** [comment]
I knew that one day I would die of UTF encoding issues.
I just didn't think that day would come so soon.
