### ISSUE TITLE
DEL behaves wrongly on blank lines.

### ISSUE THREAD

**Issue by mikelehen** [firebase/firepad#209]
Type:

foo
&lt;blank line&gt;
bar

Then put your cursor on the blank line and press DEL.  Instead of staying in place (and ending up directly before "bar"), it moves to the end of the "foo" line.

**Comment by vincentwoo** [comment]
I actually... expect this to behave the way it behaves now? Is this not how the cursor behaves on http://codemirror.net? This is also how my cursor behaves in Sublime.

**Comment by mikelehen** [comment]
@vincentwoo Uhm...  no? :-)

DEL should not ever move the cursor, and does not on codemirror.net as far as I can see.

**Comment by benwulfe** [comment]
there is both BACKSPACE and DEL.
'<==' BACKSPACE  usually moves the cursor
'.'DEL doesn't

**Comment by vincentwoo** [comment]
Ugh, Mac keyboards, sorry.

**Comment by mikelehen** [comment]
Hah, yeah.  Sorry, I never realized mac keyboards call backspace "delete."

**Comment by mikagenic** [comment]
the fix for https://github.com/firebase/firepad/issues/82 also solves this

**Comment by mikelehen** [comment]
Should be fixed, though I noticed that if you DEL and then undo, the cursor ends up in the wrong place after the undo again. :-/  Not sure if there's an easy fix for that.  We're probably abusing CodeMirror too much.

**Comment by mikagenic** [comment]
Thanks for that ! IMO the sentinel mechanism really complicates things with CM in many way and can possibly be implemented differently, for example having all the sentinels in one place in the beginning or end of the document. But I understand this will be a big rewrite.

**Comment by mikelehen** [comment]
They are complicated, but I think the only way to avoid them would be to change the data model and OT operations that firepad uses to be line/col-based instead of offset-based, which would let you you actually apply attributes to a line in the underlying data model (rather than to a "line sentinel character" that happens to be at the beginning of the line).  This would make the OT operations a little bit trickier, though still very doable...  but it's a large rewrite and would break compatibility with existing firepad data...

**Comment by cben** [comment]
If the motivation is only OT data model, it doesn't sound very complicated
to keep sentinels in the data but exclude them from the text CM sees.

Are you relying on sentinels being in CM for editing behavior e.g. for
copy-pasting a line to preserve its formatting?

2015-12-15 2:51 GMT+02:00 Michael Lehenbauer <notifications@github.com>:

**Comment by mikagenic** [comment]
What I meant was more for the sentinels to still be inside the document but as single collapsed range in one block (in the beginning of the document for example) instead of in front of each line. This will make CM line operations etc much simpler.

**Comment by mikelehen** [comment]
@cben Not relying on it for editing behavior.  I just didn't want the headache of having two data models that I have to keep in sync.  I'm afraid it would be error-prone and lead to weird edge-case bugs.

**Comment by mikagenic** [comment]
What I meant more was to keep all the sentinels in a single collapsed block 'cache' at the beginning of the document, accessed by line index etc. So it's still a single data model and inside the document but CM cursor ops etc will be much simpler .. anyways

**Comment by mikelehen** [comment]
Yeah, I have trouble imagining how that would work with the OT stuff.  If I insert text with newlines ("hello\nfoo") somewhere in the document, this will move the line sentinel characters.  By keeping them *with* the line text, this "just works" under the normal OT operations.

**Comment by mikagenic** [comment]
yeah makes sense thx :)
