### ISSUE TITLE
Release ACE 1.2.0 Support

### ISSUE THREAD

**Issue by abhishekgahlot** [firebase/firepad#213]
I can see ace 1.2.0 support is added to master but not has been released for version. Is it possible to do this asap so that I can use this directly from here instead of cloning and building myself.

Thanks

**Comment by tpof314** [comment]
That;s what I am waiting for as well.

**Comment by mikelehen** [comment]
Sorry I took so long on this, but firepad 1.3.0 is now released with Ace 1.2.x support.
