### ISSUE TITLE
Extending firepad

### ISSUE THREAD

**Issue by Immortalin** [firebase/firepad#216]
How should you start extending firepad if you want to support more editors or different input methods?

**Comment by mikelehen** [comment]
Sorry, but this question is too vague for me to answer without writing a novel. :-)  Perhaps you can be more specific on what you want to accomplish and I can provide some pointed guidance?

**Comment by Immortalin** [comment]
@mikelehen I need a way to enter custom input into firepad headlessly while still retaining all the collaborative functions of a normal DOM-based text editor e.g. keep two text files in sync. From my understanding, the headless mode is designed more for getting the contents from the editor and doing some basic configuration server-side instead of full offline use. Currently, I am trying to use Ace editor with MockRenderer but I am [not having much luck](https://github.com/ajaxorg/ace/issues/2807).

**Comment by mikelehen** [comment]
Yeah.  Firepad's headless mode let's you read/write the text, but it's not hosting an editor so there's no notion of a cursor, etc.

Have you considered using PhantomJS (a headless browser) for your application?  If you need a full editor running, that might be your best bet.

**Comment by vincentwoo** [comment]
You could also make the argument that Firepad's headless mode should know how to produce the proper diff for a `setText` call and push that to the OT doc.

**Comment by mikelehen** [comment]
Yeah.  It could also expose granular insert() / replace() methods, etc.  That seems totally reasonable.  I'm unclear on whether that'd be enough to solve @Immortalin's use case though.

**Comment by Immortalin** [comment]
@mikelehen I have the following code:
```JavaScript
var Firebase = require("firebase")
var Firepad = require("firepad")

require("amd-loader")
global.ace = require("ace/lib/ace/ace.js")
var MockRenderer = require("ace/lib/ace/test/mockrenderer").MockRenderer
var Editor = require("ace/lib/ace/editor").Editor
if (typeof process !== "undefined") {
    require("ace/lib/ace/test/mockdom")
}

var editor = new Editor(new MockRenderer())
var firepadRef = new Firebase("my-firebase-url.firebaseio.com")
var firepad = Firepad.fromACE(firepadRef, editor)
```

However, I am getting the following error:
```JavaScript
Error: Couldn't find CodeMirror or ACE.  Did you forget to include codemirror.js or ace.js?

```

**Comment by prescottprue** [comment]
@Immortalin You are attempting to create from Ace in Node (which doesn't have ACE, even though it should get strapped to global.ace when you set it). I have had problems with this when trying to use browserify/webpack along with Firepad, and have had to only call Firepad methods if `window` and `global.ace` are defined.
Have been thinking about working on a modified version of Firepad that will work with browserify/webpack potentially use [brace](https://github.com/thlorenz/brace), but haven't started anything yet.

**Comment by Immortalin** [comment]
@prescottprue any way to work around this problem? What about using mock windows etc.?

**Comment by Immortalin** [comment]
@prescottprue maybe something like [this](https://gist.github.com/mikelehen/7995843)?

**Comment by mikelehen** [comment]
I'm closing this since it's not really a specific issue and I'm not sure if it's still under discussion.  Maybe reach out to the firepad google group if you have more questions. https://groups.google.com/forum/#!forum/firepad-io
