### ISSUE TITLE
Inserting html (insertHtmlAtCursor etc) adds an extra new line at the end

### ISSUE THREAD

**Issue by kofifus** [firebase/firepad#218]
insertHtmlAtCursor etc inserts a newline (\n) after every line including the last line. The newline after the last line should not be there.

This becomes important when trying to implement a paste html functionality using insertHtmlAtCursor  instead of the default CM paste. Pasting (inserting html) inside a line gets broken because you get an extra linebreak at the end that pushes the next letter to a new line.

The pull request below solves this by changing firepad.textPiecesToInserts to not insert a newline after the last line. Also included is an updated examples\firepad.js so that this fix can be linked to from jsfiddle etc.

https://github.com/firebase/firepad/pull/217

Thx!

**Comment by mikelehen** [comment]
That PR was merged and is released in firepad 1.3.0.
