### ISSUE TITLE
Issue on typing Chinese characters

### ISSUE THREAD

**Issue by tpof314** [firebase/firepad#219]
Hi. The current Firepad integrates with a very old version of the ACE editor, which handles Chinese input badly. Sometimes I need to type non English characters such as Chinese and Japanese, but the ace editor deletes the previous row when I types a new row. This bug has been fixed in the new versions of the ACE Editor. I hope you may upgrade the ACE version. Thank you very much!!!

**Comment by mikelehen** [comment]
Thanks for the note!  I'll try to get to this soon.

**Comment by mikelehen** [comment]
I released firepad 1.3.0 which should support Ace 1.2.x.  Holler if you still have issues.
