### ISSUE TITLE
Keeping file in sync with variable

### ISSUE THREAD

**Issue by Immortalin** [firebase/firepad#223]
Hi, I am not sure whether this is the right place to ask but the issues seems relevant to sync code. Assuming that I am trying to keep two text files in sync using firepad via a virtual Dom etc., how should I keep a lock on the state of the variable? E.g. user A edits file-> file content loaded into virtual text area -> firepad receives edit -> sends to server -> await response -> user A edits file again, server has yet to reply -> server replies -> get content from text area and write to file. The problem is that things might not be kept perfectly in sync, what would be a good solution to this?

**Comment by mikelehen** [comment]
Can you elaborate on what you mean by "via a virtual Dom etc."?  The whole
point of firepad is to deal with keeping a file in sync across users.  So
I'm not clear on what you're trying to do that'll break that.

Thanks,
-Michael

**Comment by Immortalin** [comment]
I mean keeping an offline text file I.e. and actual file, not a textarea in sync

**Comment by mikelehen** [comment]
Yeah, I think that's going to be problematic.  You'd basically need to use
Operational Transforms or something to keep the file in sync with firepad
as they're both changing concurrently.  Sorry.
