### ISSUE TITLE
User List Firepad

### ISSUE THREAD

**Issue by amanuel2** [firebase/firepad#228]
When im doing User List Firepad. And copied the whole thing from the firebad userlist html file. And changed the 2 scripts to github it gave me this error:
Refused to execute script from 'https://github.com/firebase/firepad/blob/master/examples/firepad-userlist.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by mikelehen** [comment]
Try going to https://github.com/firebase/firepad/blob/master/examples/firepad-userlist.js and then clicking the "Raw" button and then using the resulting URL.

**Comment by amanuel2** [comment]
yea that worked! Thanks
