### ISSUE TITLE
adding dist to the repository

### ISSUE THREAD

**Issue by kofifus** [firebase/firepad#233]
Can we have a dist folder in the repository with firepad.js and firepad.css always updated with the latest commits ?

The main reason is to allow getting the head firepad.js/css without going through the build/grunt process.

Also it allows forking dist/firepad.js/css when posting examples ie in jsfiddle.

thanks!

**Comment by mikelehen** [comment]
I think it's generally bad practice to check in the compiled artifacts to git.  It's unnecessary and causes a lot of merge conflicts (if every PR also includes re-compiled artifacts).  Sorry!

**Comment by kofifus** [comment]
no worries ! can you pls explain here or document somewhere the build process ? I'm struggling with it ...

Also as far as https://github.com/firebase/firepad/pull/230 , igonre examples/firepad.js if you don't want it there

**Comment by kofifus** [comment]
(btw the FP docs here https://github.com/firebase/firepad (under 'what's here') sys there should be a dist directory)

**Comment by kofifus** [comment]
(sorry for many posts ...)

I am having troubles with the grunt process ... I installed all the required npm modules and then run grunt .. I get:

D:\SourceTree\firepad>grunt
Running "coffeelint:app" (coffeelint) task
[error] lib/ace-adapter.coffee:1 Line contains incorrect line endings (line_endings)
[error] lib/ace-adapter.coffee:2 Line contains incorrect line endings (line_endings)
....
[error] lib/ace-adapter.coffee:196 Line contains incorrect line endings (line_endings)
[error] lib/ace-adapter.coffee:197 Line contains incorrect line endings (line_endings)
Warning: Task "coffeelint:app" failed. Use --force to continue.

Aborted due to warnings.

any help ?

**Comment by mikelehen** [comment]
Sorry, I'm not sure what's going on.  I don't get that error.  Maybe the line-endings are messed up but my git client is normalizing them or something?  If you can figure out how to fix them, let me know.

My guess is you could get past this error by changing level: "error" to level: "warn" in Gruntfile.js for coffeelint line_endings.
