### ISSUE TITLE
setLineAttribute bug ?

### ISSUE THREAD

**Issue by kofifus** [firebase/firepad#234]
see:
 https://github.com/firebase/firepad/blob/master/lib/rich-text-codemirror.js#L172

when deleting a line attribute, if we do not have any other line attributes we also need to delete the line sentinel.

Is this a bug ?

The way the code is now we can be left with an attributes object with only a LINE_SENTINEL attribute. This then becomes an issue when trying to check if a selection is rich text (a false positive).

This may also cause other side effects on every code that iterates through the attributes.

Shouldn't the code also remove the LINE_SENTINEL attribute and the line sentinel character ?

Any recommendations on how to fix this ?

**Comment by kofifus** [comment]
also looking further isn't the LINE_SENTINEL attribute superfluous ? couldn't it be replaced with a function checking if any of the line attributes are present ? I think that will make the code better and safer

**Comment by mikelehen** [comment]
Eh, this might be a bit complicated.  There are a couple things going on:

1. Line Sentinel Characters never get deleted after you create them, even if you remove all of the attributes.  This could potentially be changed, though it will have implications on the merge behavior when multiple clients modify the line attributes at the same time.
2. All Line Sentinel Characters have the LINE_SENTINEL attribute.  This is convenient and makes some of the logic for modifying attributes easier, e.g.: https://github.com/firebase/firepad/blob/master/lib/rich-text-codemirror.js#L116

Given this state of affairs, I'd probably just manually exclude LINE_SENTINEL attribute in your code that's looking for attributes.
