### ISSUE TITLE
Set display name of a user

### ISSUE THREAD

**Issue by lorenzulrich** [firebase/firepad#240]
The `setUser` method of Firepad correctly sets a userId, but somehow it doesn't seem to be possible to set a "display name" for the user:

![image](https://cloud.githubusercontent.com/assets/1816023/13651775/1e310d82-e649-11e5-8271-6378b9b87a52.png)

How can I set this name?

**Comment by lorenzulrich** [comment]
I found it out. The userList constructor takes a 4th argument `displayName`:

`var firepadUserList = FirepadUserList.fromDiv(firepadRef.child('users'), document.getElementById(userListSelector), cleanUserId, userDisplayName);`

**Comment by monish-lota** [comment]
After set this username dynamically, I want to make username as un-editable. Help me for this.

**Comment by rair1559** [comment]
http://stackoverflow.com/questions/3676127/how-do-i-make-a-text-input-non-editable

**Comment by monish-lota** [comment]
I know how to make text box un-editable. This textbox is generate from JS. And I also know how to do this in JS. But I want to do un-editable without changing in original JS. So, any method of that can do it directly  using firepad Object.

**Comment by vincentwoo** [comment]
The Userlist is example code to use with Firepad. You can implement your own renderer or code on top of the `users` struct as you like. The original demo userlist does not support making names uneditable currently.

**Comment by monish-lota** [comment]
Ok Thank you @vincentwoo

**Comment by kratsg** [comment]
@vincentwoo - that's not correct at all. Commenting out the line here (https://github.com/firebase/firepad/blob/master/examples/firepad-userlist.js#L41) 

```
        this.makeUserEntryForSelf_(),
```

will prevent it from being editable using whatever is set. Similarly, if you also want to make sure the current user also sees themselves, go ahead and comment this line out (https://github.com/firebase/firepad/blob/master/examples/firepad-userlist.js#L130) too:

```
        userDiv.style.display = 'none';
```

**Comment by mikelehen** [comment]
I think @vincentwoo was saying that you'd need to modify the code to make user names uneditable (the code is meant as a demo rather than a fully-featured user list component), which is exactly what you have suggested.  Thanks for the pointers. Hopefully they hlep @monish-lota.

**Comment by kratsg** [comment]
@mikelehen good point, I misread. Note that I got these suggestions from the old firepad google forums before firebase was acquired. So I imagine there was some intent to allow these to be editable or not. Given it's two lines, it could really be a configuration passed in as well.
