### ISSUE TITLE
Suggested Edits

### ISSUE THREAD

**Issue by isTravis** [firebase/firepad#243]
Hi all,

Thank you again for the fantastic work and support y'all have given the community ❤️!

We're beginning to use firepad in production and one of the requests we hear a lot is for a 'Suggested Edits' feature similar to google docs. Essentially, you would be able to turn on a mode that would 1) track changes, and 2) give the user an option to accept or decline them. Accepted changes would replace the text they removed (which is perhaps visualized with a strikethrough, rather than removed), rejected changes would simply revert to the original text.

It seems like the best path may be a layer over firepad, where I keep track of positions and changes myself, and then provide an accept/decline UI, but I wanted to see if y'all had any suggestions. Is there a clever lower-level way of implementing such a feature? Have you seen others build such a thing?

Thanks so much!

**Comment by abehaskins** [comment]
I haven't seen anyone else build something similar but I'd suspect layering over (and intelligently cloning the current document) would make this possible.

I'd also learn more about Operational Transforms (we use ot.js under the hood), this will also help.
