### ISSUE TITLE
Store metadata in firebase

### ISSUE THREAD

**Issue by nitinsurana** [firebase/firepad#244]
Hi,

Searched through the docs and bugs, but couldn't find any means to store some kind of metadata in firebase using firepad. At first, thought it can only store the html/text, but then found annotations, which are a little different.

Is there any way to store some kind of meta-data information apart from the normal html/text changes ?

**Comment by mikelehen** [comment]
Can you elaborate on what kind of metadata you're talking about?  Firepad
is bulit on top of Firebase, which is a very general-purpose data
storage/sync system and so if you're just talking about document metadata
you can easily store than it Firebase using the Firebase API.

Hope this helps,
-Michael

**Comment by nitinsurana** [comment]
Worked like a charm, thanks a lot for the pointer.
