### ISSUE TITLE
Revisions started from B1b instead of A0

### ISSUE THREAD

**Issue by nitinsurana** [firebase/firepad#245]
Strangely, in all of the records stored in firebase, one of them have revisionIds starting from `B1b` instead of `A0`. 
We have created a play feature around firepad to play the revisions at an interval of 500. But since the revision are not starting from A0 it's breaking.
Went through the source-code, couldn't figure out the reason of not having revisionIds starting `A0`. Please provide a little insight.

**Comment by bhuvangu** [comment]
this is with 2.3.x or 3.0?

**Comment by nitinsurana** [comment]
Firepad latest version is 1.3 😕

**Comment by mikelehen** [comment]
Hrm.  That sounds very strange.  It should always start at A0.  My best
guess would be that somehow the revision IDs between A0 and B1b were
deleted / lost.  Do you have security rules on your app?

-Michael

**Comment by nitinsurana** [comment]
@mikelehen no security rules at this point.

**Comment by nitinsurana** [comment]
Firebase record has `history` & `checkpoint` keys. The record contains all revisions starting from A0 under history, but the checkpoint is pointing to B1b and hence, in the source-code while debugging it's giving revisions starting `B1b` I guess. Still debugging as to how come these records are having checkpoint while others aren't.

**Comment by nitinsurana** [comment]
Possibly, it's related to this one.

**Comment by nitinsurana** [comment]
Confirmed, it happens only when there are more than 100 edits. Went through the docs, but couldn't figure out how to increase the limit to say 1000 or more.

**Comment by mikelehen** [comment]
Oh!  Yeah, checkpoint is updated regularly so that when clients connect they can start at the checkpoint rather than replaying history from the beginning.  But it's always safe to replay the history starting at A0, so I'm not sure why you're needing to change the checkpoint frequency...
