### ISSUE TITLE
Docs need to be updated for 3.x

### ISSUE THREAD

**Issue by mikelehen** [firebase/firepad#250]
The docs (e.g. https://firepad.io/docs/) still reference `new Firebase(...)` even though we've updated firepad to 3.x.

**Comment by abehaskins** [comment]
I'm not seeing anything out of date in the docs? We're using 3.3.0 and show correct initialization code. Feel free to reopen if I'm missing something.

**Comment by mikelehen** [comment]
Ah, yeah.  I think @jwngr addressed this. :-)
