### ISSUE TITLE
Using CodeMirror Theme in FirePad

### ISSUE THREAD

**Issue by Redstone-Pro-73** [firebase/firepad#254]
I currently have a CodeMirror Theme that I made in CSS. I want to convert it so I can use it in FirePad. I have the default CodeMirror firepad example. Their seems to be a huge issue when I add

`theme: "coderspace",`

like this in the CodeMirror part:

```
var codeMirror = CodeMirror(document.getElementById('firepad-container'), {
    extraKeys: {"Ctrl-Space": "autocomplete"},
    lineNumbers: true,
    mode: "javascript",
    keyMap: "sublime",
    autoCloseBrackets: true,
    matchBrackets: true,
    showCursorWhenSelecting: true,
    theme: "coderspace",
    tabSize: 4,
    readOnly: false
  });
```

I also tried using other themes that are not custom designed by me. Some well known ones also did not work. Such as "monokai"

Does anyone know a way to convert or get CodeMirror themes to work in FirePad? Thank you all. Have a nice day :D

**Comment by vincentwoo** [comment]
There's no difference between adding themes in Firepad vs a vanilla CodeMirror. Are you sure you added the CSS correctly? The block of code you pasted does not even actually use Firepad, it just tries to make a vanilla CodeMirror with a theme.

**Comment by AdamMikacich** [comment]
I understand this is the vanilla part. But you create a firepad from using the vanilla part. Go look at the code example. Then you'll see the issue.

**Comment by vincentwoo** [comment]
My project uses custom CodeMirror themes in Firepad with no issues. Can you create codepen or jsfiddle that demonstrates the problem? I see no problems with the sample code you listed.
