### ISSUE TITLE
If you guys add code block detection I will love you forever

### ISSUE THREAD

**Issue by jdleo** [firebase/firepad#255]
Could actually see something like this being pretty nifty if it can detect code style. Maybe add popular programming languages for now. As far as "detect code style" , I mean being able to flick a switch, and when you do brackets, it automatically closes them 2 lines down, automatically makes variables/functions/declarations/ints/strings different colors. Pretty easy to do and I saw a sweet framework for automatically detecting/ formatting code style as you type. I guess I'll try to hack something together later.

**Comment by vincentwoo** [comment]
All of these functions are available through addons for CodeMirror and Ace, the supported editors for use with Firepad.

**Comment by vincentwoo** [comment]
All of these functions are available through addons for CodeMirror and Ace, the supported editors for use with Firepad. Here's a random example: https://codemirror.net/demo/closebrackets.html
