### ISSUE TITLE
Delayed Streaming

### ISSUE THREAD

**Issue by ziaukhan** [firebase/firepad#256]
We are developing a presentation and collaborative tool which will be using firepad with video syncing. When the author types we needs to keep it in sync with the video therefore we need to delay the text that is coming from the presenter. But the text coming from other contributors has to be in real-time. How to achieve this? Even a hint will be welcome. Thanks.

**Comment by prescottprue** [comment]
@ziaukhan Just a thought, but you could have multiple Firepad instances storing to your Firebase under different locations then have a node server use [Headless Mode](https://firepad.io/docs/#headless) to get the content from one root and place it in another.

In your case, it really only seems like you would need one main Firepad (that is all real time), and one Firepad for the presenter. Then you could have the presenter click a button to post his code to the live Firepad or have a node server do debounced updates at roughly the pace of the video.

It is just a thought, and there could be a better way. Feel free to reach out if you need help implementing.

**Comment by ziaukhan** [comment]
@prescottprue Thank you so very much, I think your idea is brilliant. I understood the main idea from the first paragraph. However, not able to understand how to copy from presenter firepad to the main firepad incrementally? Would we do something like this?
headlessPresenter.getText(function(text) {
  console.log("Contents of Presenter firepad retrieved: " + text);
  setTimeout(function(){ 
   headlessMain.setHtml(text, function(err, committed) {
  
  });
 }, timeDelay);
  
});
Thanks again.

**Comment by prescottprue** [comment]
I would go with something similar, but using `setText` instead of `setHtml` since you are getting the text from the presenter Firepad.

```js
function syncPresenterToMain() {
  headlessPresenter.getText(function(text) {
    console.log("Contents of Presenter firepad retrieved: " + text);
      headlessMain.setText(text, function(err, committed) {
        if(err) {
          console.error('Error setting text to main')
        } else {
          console.log('presenter synced to main')
        }
      });
  });
}

setTimeout(syncPresenterToMain, timeDelay))
```
or if you like es6:

```js
const syncPresenterToMain = () => 
  new Promise((resolve, reject) => {
    headlessPresenter.getText((text) =>
      headlessMain.setText(text, (err, committed) =>
        err ? reject(err) : resolve(text)
      )
    );
  })

setTimeout(() => syncPresenterToMain, timeDelay))
```

If you write it in a function like this you can also call it when the presenter clicks a button or every so often or whatever fits the application. Would be interested to check out the application and possibly provide a PR if it is something you can include me on (I understand some projects are too private for this).

**Comment by abehaskins** [comment]
Seems like @ziaukhan hasn't responded in awhile, so it looks like a solution was found :D
