### ISSUE TITLE
Freehand drawing [feature-request]

### ISSUE THREAD

**Issue by casperdcl** [firebase/firepad#263]
Hi, it would be great if there was a way to add hand-drawn graphics (e.g. svg). Maybe by making it possible to draw on a blank uploaded image.

**Comment by abehaskins** [comment]
Hey thanks for the idea! However I don't think we're looking to make major additions to Firepad right now. Feel free to try to implement this yourself and let us know if you get anywhere, I'd love to see what you make :)
