### ISSUE TITLE
potential bug in monitorHistoryStartingAt_

### ISSUE THREAD

**Issue by kofifus** [firebase/firepad#265]
In monitorHistoryStartingAt_ (https://github.com/firebase/firepad/blob/master/lib/firebase-adapter.js#L227-L244)

the problem is that we issue two async request 
- firebaseOn_(historyRef, 'child_added' ...
- historyRef.once('value', 

but rely on the second one arriving after the first one - that is for pendingReceivedRevisions_ to be full in handleInitialRevisions_

**Comment by mikelehen** [comment]
the .once('value', ...) is guaranteed to fire after all of the .on('child_added', ...) events based on Firebase's eventing guarantees.

**Comment by kofifus** [comment]
got it thx :)
