### ISSUE TITLE
Landing Page Hacked?

### ISSUE THREAD

**Issue by omranjamal** [firebase/firepad#278]
Sorry, don't know if this should be on Github but when visiting https://firepad.io/ the page changes to a disturbing animation with sudden flashes of the following...

![image](https://user-images.githubusercontent.com/4700757/27805080-44499ca6-6054-11e7-9bb6-65b9eeb619e9.png)

We'd really appreciate if you could look into it.

**Comment by prescottprue** [comment]
I am seeing this same thing

**Comment by tomlarkworthy** [comment]
As an interim solution I paused "firepad", as most of the team are on
holiday.

**Comment by ShlomoGoldshekel** [comment]
Seeing the same - shut it down please.

**Comment by mikelehen** [comment]
I'm closing this, but the landing page is still broken since the firepad instance has been enabled. I'll create a separate issue for that.
