### ISSUE TITLE
Add a spell checker

### ISSUE THREAD

**Issue by dhcar** [firebase/firepad#28]
The browser spell check doesn't recognize text inside a firepad. Either a spell check integrated into firepad or a workaround for browser spell check would be very helpful.

**Comment by kofifus** [comment]
I created a codemirror spellchecker with typo correction which will work as is with firepad.

see: [https://gist.github.com/kofifus/4b2f79cadc871a29439d919692099406](https://gist.github.com/kofifus/4b2f79cadc871a29439d919692099406)
