### ISSUE TITLE
Feature Request: Export to .docx or PDF support in firepad.

### ISSUE THREAD

**Issue by aaryanUV** [firebase/firepad#281]
Feature Request: Export to *.docx* or *PDF* support in firepad.
========================
As far as searched for it I couldn't find this feature in firepad. If wil be great if we  can port rich text document in more widely used file formats such as **.docx** and **PDF**. 

Right now this feature is provided by google docs but it is neither opensource not embeddable in website. 
Which makes google  docs editor awesome for individual users but worse for developers. So I think  adding this feature to firepad will be great. After that I plan to add Math (equation writing) support to firepad,but it will be only useful if we can take these documents from one place to other (adding export support).

Thank You !

**Comment by dguillamot** [comment]
Curious if anyone is working on this or has seen it in a Firepad plugin / fork?

**Comment by vincentwoo** [comment]
Firepad is just a synchronization later on top of codemirror or axe. You can get the value of the editor (as HTML if using rich text) and run it through the doc or off exporter of your choice. It's probably beyond the scope of this library to include that functionality by default.
