### ISSUE TITLE
cloud firestore

### ISSUE THREAD

**Issue by oosthoek** [firebase/firepad#283]
Wondering if firepad works with/ if there are plans to make it work with the new Cloud Firestore?

**Comment by mikelehen** [comment]
Unfortunately it does not currently support Firestore and we don't have concrete plans to add support at this time. It should definitely be possible to make the core text synchronization work with Cloud Firestore, but for the user list and synchronizing cursor positions, it may still make sense to use the Realtime Database as these features rely on onDisconnect support (e.g. to remove delete the cursor information when a user disconnects) for which there's no equivalent in Cloud Firestore.

**Comment by pootzko** [comment]
Just referencing #294.
