### ISSUE TITLE
Grunt tests fail with grunt-karma.js error

### ISSUE THREAD

**Issue by eklitzke** [firebase/firepad#300]
I am trying to build firepad locally using the provided build instructions. I get as far as "grunt coffee" when I get an error related to grunt-karma.js, and "grunt" fails with a similar error. I have a gist with a full log of my console activity [here](https://gist.github.com/eklitzke/53f71b6604b4c44fd2d18584e418aa15). This is on master which I just cloned, commit 2870d5d3830b8e21e56da713ad05bbf313e3acd4.

**Comment by mikelehen** [comment]
Looks like this is due to a change in karma (https://github.com/karma-runner/grunt-karma/issues/212) and can probably be fixed with:

```
npm install jasmine-core --save-dev
```

If you feel like submitting a PR, I can merge it so that the next person doesn't hit this as well. :-)
