### ISSUE TITLE
RTL text direction

### ISSUE THREAD

**Issue by benbro** [firebase/firepad#76]
Is it possible to add buttons for right-to-left and left-to-right text direction?
For right-to-left languages it's important to be able to set "direction: rtl;" in addition to "text-align:right".

I've tried manually setting the CSS but the cursor jumps from the start to the end of the line while typing.
Maybe using CodeMirror's rtlMoveVisually could help?

**Comment by nadavkav** [comment]
CodeMiror support BIDI (RTL/LTR): https://codemirror.net/demo/bidi.html
It would be very useful if you added two new buttons to the UI: RTL & LTR
(Like all major HTML editors have. see CKEditor)

**Comment by philjoseph** [comment]
Hi - any plan to add this RTL/LTR functionality ?
